
--
-- Drop database (for testing)
--
-- DROP database `tp_db`;


CREATE DATABASE IF NOT EXISTS `TP_DB`;
USE `TP_DB`;

--
-- ic_register_info
--
DROP TABLE IF EXISTS `IC_REGISTER_INFO`;
CREATE TABLE `IC_REGISTER_INFO`(
	ID VARCHAR(50) NOT NULL,
	CARD_TOKEN VARCHAR(50) DEFAULT NULL,
	CARD_ID VARCHAR(50) DEFAULT NULL,
	TRACE_NUMBER VARCHAR(100) DEFAULT NULL,
	VENDOR_CODE VARCHAR(20) DEFAULT NULL,
	PRODUCT_CODE VARCHAR(20) DEFAULT NULL,
	FULL_NAME VARCHAR(100) DEFAULT NULL,
	IC_TYPE VARCHAR(10) DEFAULT NULL,
	IC_NUMBER VARCHAR(20) DEFAULT NULL,
	OLD_IC_NUMBER VARCHAR(20) DEFAULT NULL,
	ISSUANCE_DATE VARCHAR(20) DEFAULT NULL,
	EXPIRE_DATE VARCHAR(20) DEFAULT NULL,
	ISSUE_PLACE VARCHAR(200) DEFAULT NULL,
	DATE_OF_BIRTH VARCHAR(20) DEFAULT NULL,
	GENDER VARCHAR(10) DEFAULT NULL,
	NATIONALITY VARCHAR(10) DEFAULT NULL,
	MARITAL_STATUS VARCHAR(20) DEFAULT NULL,
	FULL_ADDRESS_PERMANENT VARCHAR(200) DEFAULT NULL,
	PROVINCE_PERMANENT VARCHAR(50) DEFAULT NULL,
	DISTRICT_PERMANENT VARCHAR(50) DEFAULT NULL,
	WARD_PERMANENT VARCHAR(50) DEFAULT NULL,
	FULL_ADDRESS VARCHAR(200) DEFAULT NULL,
	PROVINCE VARCHAR(50) DEFAULT NULL,
	DISTRICT VARCHAR(50) DEFAULT NULL,
	WARD VARCHAR(50) DEFAULT NULL,
	PHONE_NUMBER VARCHAR(20) DEFAULT NULL,
	EMAIL_ADDRESS VARCHAR(50) DEFAULT NULL,
	JOB VARCHAR(100) DEFAULT NULL,
	POSITION VARCHAR(100) DEFAULT NULL,
	COMPANY_NAME VARCHAR(200) DEFAULT NULL,
	COMPANY_PHONE_NUMBER VARCHAR(20) DEFAULT NULL,
	PROVINCE_COMPANY VARCHAR(100) DEFAULT NULL,
	DISTRICT_COMPANY VARCHAR(100) DEFAULT NULL,
	WARD_COMPANY VARCHAR(100) DEFAULT NULL,
	MONTH_INCOME VARCHAR(20) DEFAULT NULL,
	PAYMENT_RATE VARCHAR(50) DEFAULT NULL,
	CREDIT_LIMIT VARCHAR(20) DEFAULT NULL,
	FULL_ADDRESS_CARD VARCHAR(200) DEFAULT NULL,
	PROVINCE_CARD VARCHAR(50) DEFAULT NULL,
	DISTRICT_CARD VARCHAR(50) DEFAULT NULL,
	WARD_CARD VARCHAR(50) DEFAULT NULL,
	SECURITY_QUESTION VARCHAR(500) DEFAULT NULL,
	SECURITY_ANSWER VARCHAR(500) DEFAULT NULL,
	PHONE_NUMBER_RELATION_1 VARCHAR(20) DEFAULT NULL,
	PHONE_NUMBER_RELATION_2 VARCHAR(20) DEFAULT NULL,
	SALARY_TYPE VARCHAR(50) DEFAULT NULL,
	ACADEMY_LEVEL VARCHAR(50) DEFAULT NULL,
	SCORE_MIMI VARCHAR(50) DEFAULT NULL,
	REF_CODE VARCHAR(100) DEFAULT NULL,
	DEVICE_ID VARCHAR(200) DEFAULT NULL,
	LOCATION VARCHAR(50) DEFAULT NULL,
	IP_ADDRESS VARCHAR(20) DEFAULT NULL,
	IMAGES VARCHAR(2000) DEFAULT NULL,
	RCODE VARCHAR(10) DEFAULT NULL,
	CIF_NUMBER VARCHAR(10) DEFAULT NULL,
	STATUS_SLS VARCHAR(50) DEFAULT NULL,
	STATUS_LANDINGPAGE VARCHAR(50) DEFAULT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	STATUS VARCHAR(50) DEFAULT NULL,
	STATUS_AML_VMS VARCHAR(50) DEFAULT NULL,
	STATUS_CHECKCIF VARCHAR(50) DEFAULT NULL,
	STATUS_CREATE_CIF VARCHAR(50) DEFAULT NULL,
	STATUS_CREATE_TKTT VARCHAR(50) DEFAULT NULL,
	STATUS_CREATE_TKCT VARCHAR(50) DEFAULT NULL,
	STATUS_CREATE_CARD VARCHAR(50) DEFAULT NULL,
	STATUS_CICS37_PCB VARCHAR(50) DEFAULT NULL,
	ACCOUNT_NO VARCHAR(20) DEFAULT NULL,
	ACCOUNT_CHUYENTHU VARCHAR(20) DEFAULT NULL,
	CARD_NUMBER VARCHAR(50) DEFAULT NULL,
	FULL_ADDRESS_COMPANY VARCHAR(160) DEFAULT NULL,
	E_SIGN_ID VARCHAR(50) DEFAULT NULL,
	LANDING_PAGE VARCHAR(200) DEFAULT NULL,
	URL_REDIRECT_SUCCESS VARCHAR(200) DEFAULT NULL,
	URL_REDIRECT_FAILED VARCHAR(200) DEFAULT NULL,
	ECM_STATUS VARCHAR(200) DEFAULT NULL,
	TYPE_PROCESS VARCHAR(100) DEFAULT NULL,
	CRM_LEAD_ID VARCHAR(200) DEFAULT NULL,
	CRM_STATUS VARCHAR(100) DEFAULT NULL,
    DELETE_FLAG BOOL DEFAULT NULL
);

--
-- ic_payment_balance_transaction
--
DROP TABLE IF EXISTS `IC_PAYMENT_BALANCE_TRANSACTION`;
CREATE TABLE `IC_PAYMENT_BALANCE_TRANSACTION` (
	ID VARCHAR(50) NOT NULL,
	CARD_ID VARCHAR(50) DEFAULT NULL,
	TRANS_TIME TIMESTAMP DEFAULT NULL,
	AMOUNT VARCHAR(100) DEFAULT NULL,
	CURRENCY VARCHAR(20) DEFAULT NULL,
	REMARK VARCHAR(100) DEFAULT NULL,
	TRACE_NUMBER VARCHAR(100) DEFAULT NULL,
	STATUS VARCHAR(20) DEFAULT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	VENDOR_CODE VARCHAR(50) DEFAULT NULL,
	FCC_REFERENCE_NO VARCHAR(50) DEFAULT NULL,
	FCC_MESSAGE_ID VARCHAR(100) DEFAULT NULL,
	FCC_STATUS VARCHAR(20) DEFAULT NULL,
	FCC_ERROR_CODE VARCHAR(20) DEFAULT NULL,
	FCC_ERROR_DESC VARCHAR(200) DEFAULT NULL,
	FCC_TRANSACTION_ID VARCHAR(50) DEFAULT NULL,
	BO2_STATUS VARCHAR(20) DEFAULT NULL,
	BO2_RESPONSE VARCHAR(20) DEFAULT NULL,
	BO2_RESPONSE_CODE VARCHAR(20) DEFAULT NULL,
	BO2_RESPONSE_DESC VARCHAR(200) DEFAULT NULL,
	BO2_RESPONSE_ID VARCHAR(50) DEFAULT NULL,
	BO2_HOST_REF VARCHAR(50) DEFAULT NULL,
	BO2_OPERATION_ID VARCHAR(50) DEFAULT NULL,
	BO2_HOST_DATE TIMESTAMP,
	FCC_RESPONSE_STATUS VARCHAR(20) DEFAULT NULL,
	BO2_RESPONSE_STATUS VARCHAR(20) DEFAULT NULL,
	FCC_REMARK VARCHAR(200) DEFAULT NULL,
	CARD_TYPE VARCHAR(20) DEFAULT NULL,
    DELETE_FLAG BOOL DEFAULT NULL
);

--
-- smv
--
DROP TABLE IF EXISTS `SMV`;
CREATE TABLE `SMV`(
	ID VARCHAR(50) NOT NULL,
	CIF_NUMBER VARCHAR(10) DEFAULT NULL,
	CARD_ID VARCHAR(50) DEFAULT NULL,
	STATUS VARCHAR(20) DEFAULT NULL,
	CARD_HOLDER_NAME VARCHAR(100) DEFAULT NULL,
	CURRENT_BALANCE VARCHAR(100) DEFAULT NULL,
	CREADIT_LIMIT VARCHAR(100) DEFAULT NULL,
	CURRENT_DEBIT_MIN VARCHAR(100) DEFAULT NULL,
	TRACE_NUMBER VARCHAR(100) DEFAULT NULL,
	DUE_DATE TIMESTAMP DEFAULT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DELETE_FLAG BOOL DEFAULT NULL
);

--
-- fcc
--
DROP TABLE IF EXISTS `FCC`;
CREATE TABLE `FCC`(
	ID VARCHAR(50) NOT NULL,
	CIF_NUMBER VARCHAR(10) DEFAULT NULL,
	IC_NUMBER VARCHAR(20) DEFAULT NULL,
	OLD_IC_NUMBER VARCHAR(20) DEFAULT NULL,
	FULL_NAME VARCHAR(100) DEFAULT NULL,
	PHONE_NUMBER VARCHAR(20) DEFAULT NULL,
	CONTRACT VARCHAR(500) DEFAULT NULL,
	SELFIE VARCHAR(2000) DEFAULT NULL,
	IC_FRONT VARCHAR(2000) DEFAULT NULL,
	IC_BACK VARCHAR(2000) DEFAULT NULL,
	TRACE_NUMBER VARCHAR(100) DEFAULT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	DELETED_FLAG BOOL DEFAULT NULL
);